Assignment : Libraries: NumPy & Pandas

Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the 
dataset information to understand its structure.

In [1]:
import pandas as pd
df = pd.read_csv("C:/Users/abhij/Downloads/retail_dataset .csv")

In [2]:
df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

In [3]:
df.tail()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
95,T096,C036,Furniture,10.0,2901.0,08-08-2023,North
96,T097,C021,Clothing,9.0,1077.0,19-07-2024,North
97,T098,C015,Clothing,7.0,643.0,13-08-2023,North
98,T099,C005,Groceries,9.0,429.0,20-01-2024,South
99,T100,C010,Furniture,8.0,1183.0,07-02-2024,North

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB

Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing 
values present in the dataset.

In [6]:
print(df.isnull().sum())

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

In [9]:
total_missing=df.isnull().sum().sum()
print("Total Missing Values",total_missing)

Total Missing Values 12

Q3. Replace missing values in the Quantity and Price columns with their respective mean values using 
Pandas.

In [14]:
df["Quantity"].fillna(df["Quantity"].mean(),inplace=True)
df["Price"].fillna(df["Price"].mean(),inplace=True)

df.isnull().sum()

C:\Users\abhij\AppData\Local\Temp\ipykernel_26484\3457167243.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Quantity"].fillna(df["Quantity"].mean(),inplace=True)
C:\Users\abhij\AppData\Local\Temp\ipykernel_26484\3457167243.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mean(),inplace=True)

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            0
Price               0
Date                0
Region              2
dtype: int64

Q4. Remove all rows where the Product Category or Region column contains missing values.

In [16]:
df.dropna(subset=['Product Category','Region'],inplace=True)

In [17]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    0
Quantity            0
Price               0
Date                0
Region              0
dtype: int64

Q5. Create a new column called Revenue using NumPy, where:
Revenue = Quantity × Price
Display the updated dataset with the new column.

In [19]:
import numpy as np

In [23]:
df['Revenue']=np.multiply(df['Quantity'],df['Price'])
print(df)

   Transaction ID Customer ID Product Category  Quantity   Price        Date Region  Revenue
0            T001        C015            Books       7.0   167.0  02-02-2023  North   1169.0
1            T002        C004             Toys       4.0   374.0  17-02-2023  South   1496.0
2            T003        C033        Furniture       8.0  1059.0  17-05-2024  South   8472.0
3            T004        C047        Groceries       5.0   304.0  11-02-2024  South   1520.0
4            T005        C022            Books       7.0   282.0  27-07-2024   West   1974.0
..            ...         ...              ...       ...     ...         ...    ...      ...
95           T096        C036        Furniture      10.0  2901.0  08-08-2023  North  29010.0
96           T097        C021         Clothing       9.0  1077.0  19-07-2024  North   9693.0
97           T098        C015         Clothing       7.0   643.0  13-08-2023  North   4501.0
98           T099        C005        Groceries       9.0   429.0  20-01-2024  South   3861.0
99           T100        C010        Furniture       8.0  1183.0  07-02-2024  North   9464.0

[95 rows x 8 columns]

Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.

In [25]:
total_revenue = np.sum(df['Revenue'])
print('Total_Revenue',total_revenue)

Total_Revenue 465529.66058002145

Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.

In [26]:
category_revenue = df.groupby('Product Category')['Revenue'].sum()
print(category_revenue)

Product Category
Beauty          27647.000000
Books           29597.938776
Clothing        85006.000000
Electronics     93204.315789
Furniture      129664.526316
Groceries       11978.000000
Sports          34484.000000
Toys            53947.879699
Name: Revenue, dtype: float64

Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the 
highest revenue and the bottom 3 categories with the lowest revenue.

In [31]:
top_3 = category_revenue.sort_values(ascending=False).head(3)
bottom_3 = category_revenue.sort_values().head(3)

print('Top 3 Categories:',top_3)
print('Bottom 3 categories:',bottom_3)

Top 3 Categories: Product Category
Furniture      129664.526316
Electronics     93204.315789
Clothing        85006.000000
Name: Revenue, dtype: float64
Bottom 3 categories: Product Category
Groceries    11978.000000
Beauty       27647.000000
Books        29597.938776
Name: Revenue, dtype: float64

Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the 
region with the highest revenue and the region with the lowest revenue.

In [34]:
region_revenue = df.groupby('Region')['Revenue'].sum()

highest_region = region_revenue.idxmax()
lowest_region = region_revenue.idxmin()

print(region_revenue)
print('Highest Revenue Region:',highest_region)
print('Lowest Revenue Region:',lowest_region)

Region
East     126232.044039
North    153244.353383
South    104855.736842
West      81197.526316
Name: Revenue, dtype: float64
Highest Revenue Region: North
Lowest Revenue Region: West

Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the 
total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column 
using NumPy

In [39]:
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

df['Month'] = df['Date'].dt.month

monthly_revenue = df.groupby('Month')['Revenue'].sum()
print('Monthly_Revenue:',monthly_revenue)

mean_rev = np.mean(df['Revenue'])
median_rev = np.median(df['Revenue'])
std_rev = np.std(df['Revenue'])

print('Mean Of Revenue:',mean_rev)
print('Median Of Revenue:',median_rev)
print('Standard Deviation Of Revenue:',std_rev)

Monthly_Revenue: Month
1     43994.000000
2     33028.000000
3     10557.000000
4     57298.526316
5     27915.000000
6     28190.000000
7     47851.292159
8     76958.000000
9     30719.105263
10    38017.000000
11    27662.736842
12    43339.000000
Name: Revenue, dtype: float64
Mean Of Revenue: 4900.312216631804
Median Of Revenue: 3282.1052631578946
Standard Deviation Of Revenue: 4721.171795257337